### ISSUE TITLE
Route 修改

### ISSUE THREAD

**Issue by linroex** [seisyo/Verthandi#4]
Route 應該要能夠串起來，並修改網址風格

Tips.
不應該是我在網址列打路徑

**Comment by linroex** [comment]
經檢查尚未完全完成

**Comment by seisyo** [comment]
這裡應該是指超連結都可以串起來吧？我記得有串了，有遺漏提醒我一下ＱＱ

**Comment by linroex** [comment]
除了超連結可以串起來之外，網址必須是正式的網址，不應該是 /event_dairy 這種網址
