### ISSUE TITLE
新增會計科目，父科目需要用選擇的

### ISSUE THREAD

**Issue by linroex** [seisyo/Verthandi#54]
Select2 for Add Account

**Comment by seisyo** [comment]
已修改，並使用select2。

**Comment by linroex** [comment]
Why not?

![2016-01-30 1 36 29](https://cloud.githubusercontent.com/assets/1254953/12683060/f344aa6e-c6f1-11e5-86a1-06a7580a6514.jpg)

**Comment by seisyo** [comment]
這我自己有新開別的issue了ＱＱ
