### ISSUE TITLE
請閱讀php coding style並修改相關格式

### ISSUE THREAD

**Issue by linroex** [seisyo/Verthandi#7]
[http://www.php-fig.org/psr/psr-2/](http://www.php-fig.org/psr/psr-2/)

ex. class name and file name

Users_detail -> UserDetail
- 去除負數
- 採用駝峰式命名

**Comment by linroex** [comment]
此外 Users.php 無需複數

**Comment by linroex** [comment]
UsersController 亦無需複數

**Comment by linroex** [comment]
middleware login_check get out

**Comment by linroex** [comment]
adduser.....
你給我好好讀完 coding style!!!!!

**Comment by seisyo** [comment]
逐步修改中......
像牽扯到migration該怎麼處理好呢？是把原本的檔案砍掉重創一個檔案嗎？（middleware也是）

**Comment by linroex** [comment]
砍掉沒錯

—林熙哲。聽風 

http://me.coder.tw
